// ─── Run Sheet strings, Phase 5-6 ────────────────────────────────────────────
// Added to RS_TR (81-rs-routes.jsx) at load. English is complete; French
// covers the Season screen, the Log sheet and the engine's jobs. Keys without
// a French line fall back to English through rt(); the list of those keys is
// in PHASE5-6-NOTES.md ("French TODO"). No em or en dashes in any line.
Object.assign(RS_TR.en, {
  close:'Close', cancel:'Cancel', add:'Add', remove:'Remove', change:'Change', find:'Find', date:'Date', live:'Live',
  current:'current', doneWord:'done', youAreHere:'you are here', allWord:'All', tryAgain:'Try again', notYet:'Not yet',
  seasonWord:'Season', todayWordL:'today', thisSeason:'this season', calcWord:'Calculator', toolsWord:'Tools',
  takes:'Takes', tapWord1:'tap', syrupToday:'Syrup made today',
  freshNoLocT:'Set your place first', freshNoLocP:'The freshness clock uses the hourly temperature where your sap sits. Set your place on Weather watch.',
  freshIdleP:'Start the clock when you collect. SweetRun adds up the heat your sap sits in and tells you when to boil.', freshStart:'Start the freshness clock',
  freshBoiled:'Boiled', freshDumped:'Dumped', freshDoneP:'The clock ran {h} h.', freshNew:'Start a new batch',
  freshClock:'Clock running', freshFresh:'Fresh', freshSoon:'Boil soon', freshNowW:'Boil now', freshErr:'Couldn\'t get the hourly temperatures. The clock keeps running.',
  freshAria:'{n} of 150 heat units', heatUnits:'Heat units', outdoor:'Outside now', boilBy:'Boil before', coolWindow:'Next cool stretch',
  fNow:'now', fInH:'in about {n} h', fInD:'in about {n} days',
  freshNote:'Heat units add up every hour the tank sits above 40°F. At 150, boil or lose it.', freshMarkBoiled:'I boiled it', freshMarkDumped:'I dumped it',
  evapOn:'Evaporator boiling, steam rising off the pans', evapOff:'Evaporator, cold', evapFlue:'Flue pan · sap in', evapSyrupPan:'Syrup pan',
  // Season home
  doNext:'Do this next', logTonight:'Log tonight', logIt:'Log it', thisStage:'This stage', howGoing:'How it\'s going', allCharts:'All charts',
  logSap:'Log sap', logSyrup:'Log syrup', logRo:'Log RO', logBrix:'Log a Brix reading',
  openStage:'Open {s}', pumpCenter:'Pump center', pumpCenterSub:'Vacuum, transfer pump, power and freeze jobs',
  seasonChart:'Season chart', dayN:'Day {n}', beforeRun:'Before the first run', syrupVsGoal:'Syrup vs goal',
  goalAria:'Syrup {p} percent of the {g} {u} goal', stageAria:'Stage {n}, {s} {w}',
  chartAria:'Sap per day this season, {n} days with sap, peak {peak} {u}',
  forecast:'Forecast', lgSap:'Sap a day', lgRun:'Good run weather', lgNoRun:'No run', lgToday:'Today',
  todayOn:'Today, {d}', sapWord:'sap', ahead:'ahead', fcWord:'forecast: {w}', noSapLogged:'no sap logged',
  wxGood:'good run weather', wxSome:'freeze and thaw', wxNone:'no run weather',
  wxStripNone:'Set your place on Weather watch to draw the run weather under the bars.',
  wxStripLoading:'Getting the run weather for the strip under the bars.',
  wxStripErr:'Couldn\'t get the weather, so the run strip is missing. The bars are your own log.',
  ctxFirst:'Let\'s set up your season. It takes about two minutes.',
  ctxBoil:'You\'re boiling. Started at {t}.', ctxFreeze:'{lo}°F tonight. Drain what could freeze.',
  ctxSapToday:'{v} {u} of sap in today.', ctxDay:'Day {n} of the run. {v} {u} of syrup so far.',
  ctxGood:'{n} good run days in the next 10.', ctxGood1:'1 good run day in the next 10.', ctxPlain:'Season {y}.',
  nBrix:'Sap Brix', nBrixSub:'{r} to 1 sap to syrup', nBoiling:'Boiling', nNotBoiling:'Not boiling', nOff:'Off', nStartBoil:'Start a boil on the Boil screen',
  nEstBoil:'syrup this boil, estimated', nSapToday:'Sap today', nEntries:'{n} entries', nEntries1:'1 entry', nNoSapToday:'Nothing logged yet today',
  nSyrupSoFar:'Syrup so far', nPerTap:'{v} {u} a tap', nNoTaps:'Set your taps in Plan & tap',
  tankNoneT:'No tank set up yet', tankNoneP:'Add your collection tank on Pumps. Its level and the RO call show here once you log a tank reading.',
  tankPinT:'{n} is pinned on the Bush tab', tankPinP:'It is on the Bush tab. Set it up on Pumps and log a reading, and its level and the RO call show here.',
  tankAdd:'Add a tank', tankSetUp:'Set it up on Pumps', tankWord:'Tank',
  tankAria:'{n}, {v} {u}, {p} percent full', fullOf:'full · {c} {u} tank', filling:'Filling', fullAt:'Full at', readAt:'Read {t}',
  svlTitle:'Syrup vs last season', svlEmpty:'No syrup logged yet this season or last.', svlNote:'Lined up on days from each season\'s first sap. {y} made {t} {u} in all.',
  svlNoPrev:'No {y} season on this device to compare with.', svlAria:'{v} {u} of syrup by day {n}, against {l} last season on the same day',
  behind:'behind {p}%',
  // engine jobs
  jSetupT:'Set up your season', jSetupW:'Tell SweetRun your taps, system and fuel. It uses them for your goal, the yield range and fuel costs.', jSetupB:'Set up season',
  jBoilT:'You\'re boiling', jBoilW:'Started at {start}, {h} ago. Draw off at {fin}°F.', jBoilB:'Open the boil', jBoilA:'Boiling since {start}', jBoilS:'Draw off at {fin}°F',
  jFreezeT:'Freezing tonight, {lo}°F', jFreezeNT:'Drain before the freeze', jFreezeW:'The low tonight is {lo}°F. Drain the RO, the transfer pump and low spots in the line before you leave.',
  jFreezeB:'Open the forecast', jFreezeA:'Freezing tonight, {lo}°F', jFreezeS:'Drain what holds sap or water',
  jRoNowT:'Run the RO', jRoNowW:'{name} is at {lvl} of {cap} {u} and fills in about {full}. A run takes {run}.', jRoNowB:'Plan the RO run', jRoNowA:'Time to run the RO', jRoNowS:'{name} at {lvl} {u}',
  jRoLaterT:'RO by {at}', jRoLaterW:'{name} fills in about {full}. Start the RO by {at} to stay ahead of it.', jRoLaterB:'Open Collect & RO', jRoLaterA:'Start the RO by {at}', jRoLaterS:'{name} at {lvl} {u}',
  jFreshT:'Sap has sat {hr} h', jFreshW24:'The freshness clock has run {h}. Boil it or run the RO before it turns.', jFreshW12:'The freshness clock has run {h}. Plan the boil.',
  jFreshB:'Open Collect & RO', jFreshA:'Sap has sat {hr} h', jFreshS:'Freshness clock started {h} ago',
  jTapWxT:'Good sap weather is coming', jTapWxW:'{n} good run days in the next 5, starting with {hi}°F after {lo}°F. Get your taps in.', jTapWxB:'Go to Plan & tap',
  jTapWxA:'Good sap weather is coming', jTapWxS:'{n} good run days in the next 5',
  jRunT1:'Sap run tomorrow', jRunT2:'Sap run in 2 days', jRunW:'A thaw to {hi}°F after a night of {lo}°F. Empty the tanks and be ready.', jRunB:'Open the forecast', jRunS:'{hi}°F after {lo}°F',
  jPreT:'Pre-season checklist', jPreW:'{done} of {total} jobs done. Finish them before the first run.', jPreB:'Open the checklist', jPreS:'{done} of {total} done',
  jPostT:'Post-season checklist', jPostW:'{done} of {total} jobs done. Clean and put away before the tubing bakes.', jPostB:'Open the checklist',
  jLocT:'Set your sugarbush location', jLocW:'Freeze warnings and the run forecast need to know where your trees are.', jLocB:'Set location', jLocS:'For freeze and run warnings',
  jMapT:'Pin your sugarbush on the Bush tab', jMapW:'Put the sugarhouse, your tank and one mainline on the Bush tab. Trees can come one at a time as you tap.', jMapB:'Open the Bush tab', jMapS:'Sugarhouse, tank and a mainline',
  jRecapT:'See how the season went', jRecapW:'Your totals, the grade mix and how this season stacks up against last.', jRecapB:'Open Recap',
  jLogT:'Log today\'s sap', jLogW:'Nothing logged yet today. It takes ten seconds.', jLogT2:'Log the day', jLogW2:'Sap in, syrup out. It takes ten seconds.', jLogB:'Log sap',
  // log sheet and history
  kSap:'Sap', kSyrup:'Syrup', kRO:'RO', kEvap:'Evaporator', kFuel:'Fuel', kHours:'Hours',
  whatLog:'What to log', somethingElse:'Something else', logKind:'Log {k}', changeEntry:'Change this entry', amountIn:'{k}, amount in {u}',
  fromWhere:'From', allPoints:'All', grade:'Grade', gradeNone:'None', syrupBrixOpt:'Syrup Brix, if you read it', sapBrixOpt:'Sap Brix, if you read it',
  onTarget:'On target, 66 to 68.9', offTarget:'Outside 66 to 68.9', noteOpt:'Note, if you want one', addNote:'Add a note',
  saveAmt:'Save {v} {u} of {k}', saveKind:'Save {k}', saveChange:'Save the change', deleteEntry:'Delete this entry', tapAgainDelete:'Tap again to delete',
  savedEntry:'Saved {v} {u} of {k}', entryChanged:'Entry changed', entryDeleted:'Entry deleted',
  pickSeason:'Season', showKind:'Show', allKinds:'All', collectionPoint:'Collection point', entries:'Entries',
  noEntriesT:'Nothing logged this season', noEntriesP:'Every sap run, boil and batch you log lands here, newest first.',
  noEntriesFT:'Nothing matches', noEntriesFP:'Try All, or log one now.', logSomething:'Log something',
  entryAria:'{k}, {v} {u}, {d}. Tap to change or delete.', showMore:'Show {n} more',
  exportImport:'Export and import', exportCsv:'Export {y} as CSV', exportCsvS:'Every entry, for a spreadsheet', exportPdf:'Export the {y} season PDF', exportPdfS:'Totals, charts and entries',
  importMon:'Import sap monitor data', importMonS:'CSV or PDF, duplicates skipped',
  autoCopy:'Auto-copy sap', acRO:'Copy sap into RO', acEvap:'Copy sap into the evaporator', acSub:'Adds the same amount when you log sap',
  collectionPoints:'Collection points', cpLede:'Keep sap from separate tanks or pumphouses apart. Pick one when you log sap.',
  cpNew:'Name of the new collection point', cpPh:'Pumphouse 1, north woods', cpMax:'Six collection points is the most.',
  // stages, shared
  wxLede:'Watch for warm days after cold nights. That\'s your signal to tap.',
  goodDays10:'Good sap days, next 10', ofN:'of {n}', updatedAt:'Updated {t}',
  runRule:'A good run needs a day of 40°F or more after a night of 28°F or less.',
  wxAria:'Low {lo}, high {hi}', wxBarsNote:'The line marks 32°F. Bars run from the night\'s low to the day\'s high.',
  wxGoodRun:'Good run', wxFreezeThaw:'Some run', wxTooWarm:'Too warm', wxAllFreeze:'Stays frozen', wxNoRun:'No run',
  wxErrT:'Couldn\'t get the forecast', wxErrP:'No signal, or the weather service is down. Try again when you have a bar or two. Everything else still works.',
  yourPlace:'Your sugarbush', forecastFor:'Forecast for this place', whenToTap:'When to tap',
  firstSapOn:'First sap on {d}', firstSapP:'Day {n} of the run today.',
  streakOn:'Two good days in a row start {d}', streakP:'Two thaws in a row after freezing nights usually start the sap moving.',
  noStreak:'No good run pair in the next 10', noStreakP:'Keep watching. Taps can wait for the first warm spell.',
  tonight:'Tonight', freezeTonight:'Freezing tonight, {lo}°F', freezeTonightS:'Drain the RO, pumps and low spots before dark',
  noFreezeTonight:'Low of {lo}°F tonight', noFreezeTonightS:'No hard freeze on the way',
  moreWeather:'More weather', goTap:'Go to Plan & tap',
  setPlaceT:'Where is your sugarbush?', setPlaceP:'The forecast, freeze warnings and the run strip on the Season chart use this place.',
  placeSearch:'Town or zip code', placePh:'Town or zip code', placeNotFound:'Couldn\'t find that place. Try a nearby town or a zip code.',
  searchFailed:'Search failed. Check your signal and try again.', useGps:'Use my location', noGps:'This device can\'t share its location.',
  gpsDenied:'Location is turned off for SweetRun. Allow it in your settings, or search by town.', gpsFailed:'Couldn\'t get your location. Search by town instead.',
  // plan and tap
  tapLede:'Taps per tree, the trees you have pinned, and what each one needs.',
  tapsPlanned:'Taps this season', tapsWord:'taps', tapsWordC:'Taps', onMapN:'{n} trees pinned', noneOnMap:'No trees pinned',
  tapsMapped:'{t} taps on {n} mapped trees', treesTaps:'{t}\u00a0trees · {n}\u00a0taps', ttTree1:'1\u00a0tree', ttTreeN:'{t}\u00a0trees', ttTap1:'1\u00a0tap', ttTapN:'{n}\u00a0taps', tapsSetting:'Taps this season is your setting, used for your goal and yield per tap.',
  howManyTaps:'How many taps', dbhLabel:'Diameter at chest height', dbhU10:'Under 10 in', dbhU10s:'Leave it for now', dbh10:'10 to 17 in', dbh18:'18 to 24 in', dbh25:'25 in and up',
  dbhNote:'The same rule the tapping guide uses. Vacuum adds sap per tap, not taps per tree.',
  treesWord:'Trees', treeWord:'Tree', noTreesT:'No trees pinned yet', noTreesP:'Drop tree pins on the Bush tab as you tap. Each one gets its tag, size and taps here.',
  findTree:'Find a tree', findTreePh:'Find a tag or name', filterTrees:'Filter trees', fAll:'All', fTwo:'2+ taps', fLook:'Needs a look', fNone:'No taps',
  noTreeQ:'No tree called "{q}"', noTreeF:'No trees in this filter', noTreeHint:'Tags are the tag you gave the pin on the Bush tab.', showAllTrees:'Show all trees',
  nTap1:'1 tap', nTaps:'{n} taps', needsLook:'needs a look', showAllN:'Show all {n} trees', mainlineN:'Mainline {id}', noMainline:'No mainline',
  tapDetail:'Tapping guide and records', addTreesBush:'Add trees on the Bush tab',
  nameWord:'Name', species:'Species', diameter:'Diameter', mainlineWord:'Mainline', health:'Health', added:'Added', showOnBush:'Show on the Bush tab',
  // lines and tanks
  linesLede:'Your mainlines, what they carry, and the tanks at the end of them.',
  bushCounts:'Mainlines {m} · Pins {p} · Tanks {t}', mainlines:'Mainlines', noLinesT:'No mainlines yet', noLinesP:'Draw your first mainline on the Bush tab.',
  noTreesOnLine:'No trees assigned yet', linesNote:'Line colours are the ones you picked on the Bush tab.', tanksWord:'Tanks', onTheMap:'On the Bush tab',
  tubingWord:'Tubing', importKml:'Import lines from KML or GPX', importKmlS:'On the Bush tab, under Property', importKmlS2:'Property lines, on the Bush tab',
  drawLine:'Draw a line on the Bush tab', offlineTiles:'Save the Bush for no signal', offlineTilesS:'Offline imagery, on the Bush tab',
  // collect and RO
  collectLede:'Check the tank, run the RO in time, and keep an eye on Brix at the trees.',
  theRoCall:'The RO call', openRoPlanner:'Open the RO planner',
  roCallNow:'Run the RO now', roCallKeep:'Keep collecting', roCallTank:'{n} is at {v} of {c} {u}.',
  roTodayT:'RO today\'s sap', roTodayW:'{v} {u} of sap at {b}% makes about {c} {u} of concentrate at {tb}%, and about {s} {u} of syrup.',
  roNoSapT:'Log sap to plan the RO', roNoSapW:'Once today\'s sap is in, SweetRun works out the concentrate and the syrup it makes.',
  brixAtTree:'Brix at the tree', lastReading:'Last reading, {d}', brixSetting:'Your sap Brix setting', sapForOne:'Sap for 1 {u} of syrup',
  brixTrendAria:'Sap Brix over {n} readings', brixNote:'Brix is the sugar in the sap from a refractometer. It usually drifts down as the season runs.',
  todaysLog:'Today\'s log', nothingToday:'Nothing logged today', nothingTodayP:'Log sap as it comes in. It lands here and on the Season chart.',
  sapFresh:'Sap freshness', sapBrixPct:'Sap Brix, %', brixNotePh:'Tree tag or where you read it', saveBrix:'Save the reading', savedBrix:'Saved {v}% Brix',
  sapThrough:'Sap through the RO, {u}', concTo:'Concentrate to, % Brix', roInvalid:'Concentrate Brix ({t}) has to be above sap Brix ({s}). The RO concentrates, it doesn\'t dilute.',
  whatComesOut:'What comes out', concentrate:'Concentrate', atBrix:'at {b}% Brix', waterOut:'Water out', pctRemoved:'{p}% removed, {x} times as sweet',
  whatItSaves:'What it saves', boilSaved:'Boil time saved', fuelSavedW:'Fuel saved', evapRate:'Evaporator rate', setPanFirst:'Set your pan on the Evaporator screen',
  roSavesNote:'At your fuel cost of ${c} a {f} and your pan\'s rate. Boil time from the Rule of 86.',
  multiPass:'More passes', pass1:'One pass', pass2:'Two passes', pass3:'Three passes',
  roTips:'Run it at 40 to 50°F and 150 to 250 PSI. Rinse the membrane after every run. Past 12 to 15 Brix, niter starts to build.',
  // boil
  boilLede:'Draw off at the right temperature, press the syrup, and log each batch.',
  boilCard:'Today\'s boil', boilingSince:'Boiling since {t}', customPan:'Custom pan', syrupThisBoil:'Syrup this boil, estimated',
  perHour:'+{v} {u} an hour', paused:'paused', jugsAria:'{v} {u} of syrup this boil, estimated',
  estNote:'Estimated from your pan\'s rate boiling {b}% sap. Syrup you draw and count is the real number.',
  panTemp:'Pan temperature', bsWarming:'Warming up', bsNear:'Getting close', bsDraw:'Draw off now', bsOver:'Past the mark',
  sapIn:'Sap in', syrupDrawn:'Syrup drawn', endBoil:'End the boil', startBoil:'Start a boil',
  drawOffAt:'Draw off at', waterBoilsAtV:'Water boils at {v}{u}', drawOffP:'Water\'s boiling point plus 7.1°F. Check the hydrometer before you jar it.',
  recheckWater:'Boil point', hydroFix:'Hydrometer fix', todaysBoil:'Today\'s boil', nSapBoiled:'Sap boiled', nBoilHours:'Boil hours',
  filterPress:'Filter press', deCalc:'DE calculator', deCalcS:'How much filter aid to use', finishGuideS:'Density, grades, canning and candy',
  batchesWord:'Batches', noBatchesT:'No batches yet', noBatchesP:'Record a batch when you draw off and jar it. Each one gets a label with a QR code.',
  recordBatch:'Record a batch', endSummary:'End of the boil', duration:'Time boiling', ratioWord:'Sap to syrup',
  logBoilNote:'Adds the sap boiled, the syrup drawn and the hours to your log.', logThisBoil:'Log this boil',
  discardBoil:'Throw this boil away', discardArm:'Tap again to throw it away', boilLogged:'Boil logged: {v} {u} of syrup',
  batchSap:'{v} {u} sap', labelFor:'Download the label for batch {n}', deleteBatch:'Delete batch {n}',
  syrupOut:'Syrup out, {u}', sapInOpt:'Sap in, {u}, if you know it', placeWord:'Where', placeBatchPh:'Town, state', saveBatch:'Save the batch',
  batchSaved:'Batch {n} saved', batchesTitle:'Batches and labels', batchesSub:'Grades, Brix and QR labels',
  batchesLede:'Every batch you record, with a printable label that links to its story.',
  // draw-off and hydrometer
  drawOffC:'{c}°C', waterBoilsAtL:'Water boils at, °F', bpNote:'Boil a pot of water and read your thermometer. Weather moves this a degree or two in a day.',
  fromAltitude:'From your altitude', elevFailed:'Couldn\'t get your elevation. Enter it below.', elevAt:'{p}, about {ft} ft up', altitudeFt:'Altitude, ft',
  altRow:'{bp}°F, draw off {fin}°F', hydroReads:'Hydrometer reads', syrupAt:'Syrup temperature', correctedTo:'Corrected Brix',
  densityOk:'Legal density', densityLight:'Too light', densityHeavy:'Too heavy',
  corrAdd:'At {t}°F, add {v} to the reading.', corrSub:'At {t}°F, take {v} off the reading.', legalRangeNote:'Legal maple syrup runs from 66.0 to 68.9 Brix.',
  brixBaume:'Brix and Baumé', brixToBe:'{b} Brix is', baumeIn:'Or enter Baumé', beToBrix:'That is {b} Brix.',
  beHotNote:'Cold test at 60°F. The same syrup reads about 32.0 Bé hot at 211°F.',
  // DE
  deGal:'Syrup to filter', deMethod:'Method', deStraight:'Straight mix', dePrecoat:'Precharge first',
  deRecStraight:'At {v} {u} or less, straight mix works well.', deRecPre:'Over {v} {u}, precharging the plates pays off.',
  deColor:'Syrup colour', deEarly:'Light or amber', deLate:'Dark or very dark', dePlates:'Number of plates', dePlateSize:'Plate size',
  deYouNeed:'You need', deCups:'cups of DE', deTbsp:'Tablespoons', deOz:'Ounces', deLb:'Pounds', deLateNote:'Late season rate: dark syrup needs more DE.',
  deHow:'How to do it',
  deS1:'Heat the syrup to 185 to 190°F.', deS2:'Measure {cups} cups of food grade filter DE.', deS3:'Stir the DE into the hot syrup until no clumps are left.',
  deS4:'Start the press slowly.', deS5:'Run the cloudy first syrup back into the pot until it runs clear.', deS6:'Stop at 40 PSI. The plates are full.',
  deP1:'Put 1 to 2 gallons of 150 to 170°F water in the press.', deP2:'Stir {cups} cups of DE into that water.', deP3:'Circulate it until the water runs clear. The plates are coated.',
  deP4:'Drain the water. Don\'t disturb the plates.', deP5:'Heat the syrup to 185 to 190°F and start filtering.', deP6:'Stop at 40 PSI, rinse and precharge again for more syrup.',
  dePsi:'Use filter press DE only. Pool DE is not food safe.',
  // recap
  recapLede:'The {y} season in numbers.', recapEmptyT:'Nothing logged for {y} yet', recapEmptyP:'Log sap and syrup through the season and this page fills in.',
  goalLine:'Goal {g} {u}: {t} taps at the middle of the {m} range.', perTapW:'Per tap', sapCollected:'Sap collected', avgBrix:'Average Brix', nReadings:'{n} readings',
  seasonGrade:'Season grade', scoreWord:'SweetRun score', gradeAria:'Grade {g}',
  subYield:'Yield per tap', subEff:'Evaporator efficiency', subFuel:'Fuel', subData:'Data logged', subDataV:'{n} of 4',
  noGradeT:'No grade yet', noGradeP:'The score needs sap, syrup and at least one more of taps or fuel logged before it grades a season.',
  suspectT:'These entries don\'t add up', suspectP:'{r} to 1 sap to syrup is under what any sap can make ({f} to 1). One entry is likely in the wrong box. No grade until it\'s fixed.',
  checkEntries:'Check the entries', byGrade:'By grade', gradeMixAria:'Syrup by grade', noGradeGiven:'No grade given',
  sapADay:'Sap a day', uLast:'{u} last day', peakV:'peak {v}', sapDayAria:'Sap collected per day over {n} days',
  perTapTitle:'Syrup per tap', galTap:'gal a tap', usAvg:'US average {v}', usWord:'US', nassNote:'US average for all methods from USDA NASS.',
  perTapAria:'Syrup per tap so far this season against the US average',
  sugarInSap:'Sugar in the sap', pctLast:'% last reading', fromFirst:'from {v} at first', brixDrift:'Sap Brix usually drifts down as the season runs.',
  moreRecap:'Score detail, replay and diagnose',
  // shack
  secData:'Data', firstNamePh:'Leave blank for no name', unitsWord:'Units', gallons:'Gallons', litres:'Litres',
  unitsNote:'Entries keep the unit you logged them in. Switching doesn\'t change past entries.',
  langWord:'Language', seasonYear:'Season', prevSeason:'Previous season', nextSeason:'Next season',
  boilScreen:'Boil screen', photoSteam:'Photo and steam', justSteam:'Just steam',
  sapWordC:'Sap, {u}', sharedBrix:'Sap Brix is shared with every calculator.', makesAbout:'Makes about', uSyrup:'{u} syrup',
  ratioLine:'{r} {u} of sap for each {u} of syrup.', rule86:'Rule of 86', jones:'Jones rule (87)', perTapN:'Per tap ({n} taps)',
  rule86Note:'Rule of 86 with the divisor this app has always used (86.4). A change to the formula is its own decision.', quickRef:'Quick reference',
  tasksLede:'Before and after the {y} season.', preSeasonW:'Before the season', postSeasonW:'After the season', doneOf:'{d} of {n} done',
  removeTask:'Remove this job', addTask:'Add a job', addTaskPh:'Add your own job', resetList:'Clear the {y} ticks',
  equipLede:'What you own, and how long the transfer pump takes to move a tank.', whatYouOwn:'What you own',
  noEquipT:'Nothing listed yet', noEquipP:'Add the evaporator, RO, pumps and tanks. It\'s your inventory for insurance and next year\'s list.',
  addEquip:'Add equipment', deleteItem:'Delete {n}', transferTime:'Transfer time', pumpGpm:'Pump rate', tankGal:'Tank size', lineFt:'Line length', liftFt:'Lift',
  setupMin:'Setup time', realistic:'Realistic', theoretical:'Theoretical', fillSetup:'{f} min to fill plus {s} min setup', flowDrop:'line and lift cut flow to {g} gpm',
  haulsSeason:'Hauls in {y}', haulTime:'Hauling time', avgHaul:'Average haul', haulNoSap:'Log sap to see hauls for the season.',
  haulNote:'Hauling at 90% of the tank, {g} gal.', equipName:'Name', equipNamePh:'Evaporator 2x8', brand:'Brand', yearWord:'Year', qty:'Quantity', condition:'Condition',
  saveEquip:'Save', equipSaved:'{n} added',
  backupLede:'Everything lives on this device only ({n} entries). Download a backup after any day you care about. It\'s the only copy.',
  notPersisted:'This browser hasn\'t promised to keep your data. Add SweetRun to your home screen and keep backups.',
  backupDl:'Download a backup', restoreFrom:'Restore from a backup', backupDone:'Backup downloaded, {n} entries. Keep it somewhere safe.',
  backupBad:'That file doesn\'t look like a SweetRun backup.', restoreQ:'Restore {n} entries from {d}?', restoreWarn:'Matching data on this device will be replaced. The app reloads after.',
  restoreGo:'Restore and reload',
});
Object.assign(RS_TR.fr, {
  close:'Fermer', cancel:'Annuler', add:'Ajouter', remove:'Retirer', change:'Changer', find:'Chercher', date:'Date', live:'En direct',
  current:'en cours', doneWord:'terminée', youAreHere:'vous êtes ici', allWord:'Tout', tryAgain:'Réessayer', notYet:'Pas encore',
  seasonWord:'Saison', todayWordL:'aujourd\'hui', thisSeason:'cette saison', calcWord:'Calculateur', toolsWord:'Outils',
  doNext:'À faire maintenant', logTonight:'Noter ce soir', logIt:'Noter', thisStage:'Cette étape', howGoing:'Comment ça va', allCharts:'Tous les graphiques',
  logSap:'Noter l\'eau d\'érable', logSyrup:'Noter le sirop', logRo:'Noter l\'osmose', logBrix:'Noter une lecture Brix',
  openStage:'Ouvrir {s}', pumpCenter:'Centre des pompes', pumpCenterSub:'Vacuum, pompe de transfert, énergie et gel',
  seasonChart:'Graphique de saison', dayN:'Jour {n}', beforeRun:'Avant la première coulée', syrupVsGoal:'Sirop et objectif',
  forecast:'Prévision', lgSap:'Eau d\'érable par jour', lgRun:'Temps de coulée', lgNoRun:'Pas de coulée', lgToday:'Aujourd\'hui',
  todayOn:'Aujourd\'hui, {d}', sapWord:'d\'eau d\'érable', ahead:'à venir', noSapLogged:'aucune eau d\'érable notée',
  ctxFirst:'Configurons votre saison. Environ deux minutes.', ctxBoil:'Vous bouillez depuis {t}.', ctxFreeze:'{lo}°F cette nuit. Videz ce qui peut geler.',
  ctxSapToday:'{v} {u} d\'eau d\'érable aujourd\'hui.', ctxDay:'Jour {n} de la coulée. {v} {u} de sirop jusqu\'ici.', ctxGood:'{n} bonnes journées de coulée dans les 10 prochains jours.',
  ctxGood1:'1 bonne journée de coulée dans les 10 prochains jours.', ctxPlain:'Saison {y}.',
  nBrix:'Brix de l\'eau d\'érable', nBrixSub:'{r} pour 1, eau à sirop', nBoiling:'Bouillage', nNotBoiling:'Pas de bouillage', nOff:'Arrêt', nStartBoil:'Démarrez sur l\'écran Bouillage',
  nEstBoil:'sirop de ce bouillage, estimé', nSapToday:'Eau d\'érable aujourd\'hui', nNoSapToday:'Rien de noté aujourd\'hui', nSyrupSoFar:'Sirop jusqu\'ici', nPerTap:'{v} {u} par entaille',
  tankNoneT:'Aucun réservoir configuré', tankAdd:'Ajouter un réservoir', tankSetUp:'Configurer dans Pompes',
  svlTitle:'Sirop et saison dernière', behind:'en retard de {p} %',
  jSetupT:'Configurer votre saison', jSetupB:'Configurer', jBoilT:'Vous bouillez', jBoilB:'Ouvrir le bouillage',
  jFreezeT:'Gel cette nuit, {lo}°F', jFreezeNT:'Vider avant le gel', jFreezeB:'Voir la prévision', jFreezeA:'Gel cette nuit, {lo}°F',
  jRunT1:'Coulée demain', jRunT2:'Coulée dans 2 jours', jRunB:'Voir la prévision',
  jLogT:'Noter l\'eau du jour', jLogW:'Rien de noté aujourd\'hui. Dix secondes suffisent.', jLogT2:'Noter la journée', jLogW2:'L\'eau entre, le sirop sort. Dix secondes suffisent.', jLogB:'Noter l\'eau d\'érable',
  jLocT:'Indiquer l\'emplacement de l\'érablière', jLocB:'Indiquer', jMapT:'Cartographier l\'érablière', jMapB:'Ouvrir l\'onglet Érablière',
  kSap:'Eau d\'érable', kSyrup:'Sirop', kRO:'Osmose', kEvap:'Évaporateur', kFuel:'Combustible', kHours:'Heures',
  whatLog:'Quoi noter', somethingElse:'Autre chose', logKind:'Noter : {k}', changeEntry:'Modifier l\'entrée', fromWhere:'Provenance', allPoints:'Tous',
  grade:'Classe', gradeNone:'Aucune', noteOpt:'Note, au besoin', addNote:'Ajouter une note', saveAmt:'Enregistrer {v} {u} ({k})', saveKind:'Enregistrer : {k}',
  saveChange:'Enregistrer la modification', deleteEntry:'Supprimer l\'entrée', tapAgainDelete:'Touchez encore pour supprimer', savedEntry:'{v} {u} enregistrés ({k})',
  entryChanged:'Entrée modifiée', entryDeleted:'Entrée supprimée',
  wxGoodRun:'Bonne coulée', wxFreezeThaw:'Coulée partielle', wxTooWarm:'Trop chaud', wxAllFreeze:'Reste gelé', wxNoRun:'Pas de coulée',
  gallons:'Gallons', litres:'Litres', unitsWord:'Unités', langWord:'Langue', boilScreen:'Écran Bouillage', photoSteam:'Photo et vapeur', justSteam:'Vapeur seulement',
  secData:'Données', startBoil:'Démarrer un bouillage', endBoil:'Terminer le bouillage', drawOffAt:'Soutirer à', recordBatch:'Noter un lot',
});
