// ─── Run Sheet strings, Phase 6 rebuild ──────────────────────────────────────
// English for every screen that replaced a classic embed: forecast, degree
// days, tapping guide, tubing, evaporator, finishing, break-even, recap detail,
// diagnose, sugaring guide, Season Pass, first-season setup and import.
// French is not written yet: rt() falls back to English and the key list is in
// PHASE5-6-NOTES.md ("French TODO"). No em or en dashes in any line; numbers
// arrive already formatted.
Object.assign(RS_TR.en, {
  backW:'Back', nextW:'Next', notNow:'Not now', clearW:'Clear', yesW:'Yes', noW:'No', totalW:'Total', hiW:'High', loW:'Low', daysW:'days',
  syrupMadeW:'Syrup made', evPan:'Pan size', evFuelT:'Fuel', noteSaved:'Note saved', rotSaved:'Rotation saved', saveNote:'Save note',
  deleteNote:'Delete this note', deleteReading:'Delete this reading', perUnit:'{p} a {u}', uPerTap:'{u} a tap', noRatio:'no ratio yet',
  set_import_s2:'SugarCalc PDF, SapSpy, SapTrac or any CSV', wzSaved:'Season plan saved',
  // Forecast
  fcLede:'Every day scored for sap flow from the freeze, the thaw, the swing, sun, wind and rain.',
  fcRunDays:'Run days, next 7', fcBest:'Best score', fcPickDay:'Pick a day', fcDayAria:'{d}, score {s}, {q}',
  fcBarsNote:'Orange bars are run days, 44 and up. Tap a day for why it scored that way.',
  fcModelNote:'Scored on sugar maple physiology from Cornell and UVM Proctor research. Your bush may run a little different.',
  qExcellent:'Excellent run', qGood:'Good run', qFair:'Fair run', qPoor:'Poor run', qNoFlow:'No flow',
  fNight:'Night freeze', fDay:'Day thaw', fSwing:'Swing', fWind:'Wind', fRain:'Rain', fSun:'Sun',
  fIdeal:'ideal', fVeryCold:'very cold', fLightFreeze:'light freeze', fNoFreeze:'no freeze', fBuddy:'bud risk', fMarginal:'marginal thaw', fNoThaw:'no thaw',
  fExcellent:'excellent', fGood:'good', fLimited:'limited', fCalm:'calm', fLightWind:'light', fCutsFlow:'cuts flow', fDry:'dry', fLightRain:'light rain', fHeavyRain:'heavy rain',
  fSunny:'sunny', fPartSun:'some sun', fOvercast:'overcast',
  buddyT:'Warm enough to start bud break', buddyP:'Highs over 50°F can wake the trees and turn the sap. Taste it and watch the buds.',
  ribbonT:'Freeze and thaw, 7 days', ribbonNote:'Shaded days freeze to 28°F or lower and thaw to 40°F or higher. That is a run.',
  ribbonAria:'Highs and lows for 7 days, {n} run days shaded', lgHigh:'High', lgLow:'Low', lgRunDay:'Run day',
  handT:'Check a day by hand', handHi:'Day high', handLo:'Night low',
  hand_excellent:'Excellent run likely', hand_good:'Good flow likely', hand_marginal:'Marginal', hand_poor:'Poor for flow',
  moneyT:'Money', bevTitle:'Break-even', bevSub:'What you need to make to cover the season',
  // Degree days and Brix
  ddLede:'How much warmth the season has had since you tapped, and how sweet the sap is running.',
  ddTitle:'Degree days', ddPlaceT:'Where to count degree days', ddPlaceP:'Search a town or use GPS. This place is kept apart from your forecast place.',
  ddPlaceSub:'Degree days for this place', ddUseWx:'Use {p}', ddStart:'Count from', ddUseFirst:'Use first sap day, {d}',
  ddErrT:'Couldn\'t load the weather history', ddErrP:'Check your connection, or pick a start date in the past.',
  ddIdleT:'Pick a place and a start date', ddIdleP:'Degree days add up the warmth above 40°F each day from the day you tapped.',
  ddTotal:'Degree days', ddDays:'Days', ddAvg:'A day', ddDaily:'Day by day ({n})',
  dd_open:'Season opening', dd_open_n:'First runs are possible', dd_early:'Early season', dd_early_n:'Runs are getting better',
  dd_peak:'Peak season', dd_peak_n:'The best run weather', dd_late:'Late season', dd_late_n:'Brix is dropping. Watch for buddy sap',
  dd_end:'Season end likely', dd_end_n:'Trees will bud soon',
  brixTrendT:'Brix trend', latestReading:'Latest reading', peakBrixV:'peak {v}%',
  brixNoneT:'No Brix readings yet', brixNoneP:'Log a refractometer reading at the trees or the tank. It shows here as a trend.',
  buddyDropT:'Brix is falling fast', buddyDropP:'Down to {l}% from a peak of {p}%. Check the sap for cloudiness and taste.',
  // Tapping guide
  tgLede:'How many taps your trees can take, the right bit and depth, and notes on each tree.',
  tgTrees:'Trees', tgDbh:'Trunk size', tgVac:'Tap system',
  tgv_gravBuckets:'Gravity', tgv_gravBuckets_s:'or buckets', tgv_lowVac:'Low vacuum', tgv_lowVac_s:'under 15 in', tgv_highVac:'High vacuum', tgv_highVac_s:'15 in and up', tgPerTree:'Taps a tree', tgTotal:'Total taps', tgSap:'Sap this season', tgSyrup:'Syrup this season',
  tgEstNote:'At {r} to 1 and the {m} yield. The tree count is shared with the rest of the app.',
  tgSizeT:'Smallest tree to tap', tgSpoutT:'Spout and bit', tgBit:'Drill bit', tgDepth:'Depth',
  tgDrillT:'Drilling', tgNotesT:'Tree notes', tgNotesNoneT:'No tree notes yet', tgNotesNoneP:'Note a tree that runs well, runs thin, or needs a year off.',
  tgNoId:'No tree ID', tgAddNote:'Add a tree note', tgTreeId:'Tree ID or name', tgTreeIdPh:'Big maple by the gate', tgTags:'Quick tags', tgObs:'What you saw', tgObsPh:'Anything else',
  tgRotT:'Tap rotation', tgRotP:'Tap the other side of the tree next year so the wood heals.',
  tgRotNoneT:'No rotation logged', tgRotNoneP:'Log which side you tapped and the app tells you the side for next year.',
  tgRotLine:'Tapped {s}. Next year {n}', tgAddRot:'Log a tapped side', tgSide:'Side',
  // Tubing
  tuLede:'Mainline size, vacuum at the far tap, pump size and a materials list.',
  tuTaps:'Taps', tuMain:'Mainline length', tuGrade:'Downhill grade', tuVac:'Vacuum at the tap', tuLat:'Taps a lateral',
  tuInNote:'Length is pump to the farthest tap. Grade is the slope toward the tank.',
  tuEmptyT:'Enter taps and mainline length', tuEmptyP:'Or start from a typical bush and adjust.',
  tuPre_small:'Small woodlot', tuPre_mid:'Mid size', tuPre_large:'Large operation',
  tuVacT:'Vacuum', tuTarget:'Target at the tap', tuLoss:'Line loss', tuAssist:'Grade assist', tuPumpVac:'Pump needs to pull',
  tuEasy:'Easy', tuHigh:'High', tuHard:'Too high',
  tuPumpHighP:'That is a lot to ask of one pump. Go up a mainline size or add a pump partway.',
  tuGradeP:'Your {ft} ft of drop gives real natural vacuum.',
  tuMainT:'Mainline', tuMainLine:'{s} inch ({mm} mm)', tuMainFor:'For {t} taps on {ft} ft of mainline',
  tuLatT:'Laterals', tuLatFt:'{ft} ft of lateral', tuPumpT:'Vacuum pump',
  tu_p10:'A ½ HP rotary vane pump', tu_p20:'A 1 HP rotary vane pump', tu_p40:'A 2 HP rotary vane pump', tu_p75:'A 3 to 5 HP rotary vane pump', tu_pBig:'A large system, {c} CFM or more',
  tuMatT:'Materials', tuMatMain:'Mainline tubing, {s}', tuMatLat:'Lateral tubing, 5/16"', tuMatDrop:'Drop lines, 5/16"', tuMatTee:'Tee fittings', tuMatCap:'Lateral end caps',
  tuWaste:'Includes 10% extra', tuDropNote:'About 4 ft a tap', tuTeeNote:'One a tap', tuCapNote:'One a lateral',
  tuSource:'Cornell Maple Program guidelines, 8 ft between trees. Check exact amounts with your dealer.',
  // Evaporator
  evLede:'Your pan\'s boiling rate, how long a batch takes, fuel, what a gallon costs you and what to charge.',
  evCustom:'Custom', fuelGas:'Gas', evYourSize:'your size', evWidth:'Pan width', evLength:'Pan length', evOwnRate:'Your own rate, if you know it',
  evOwnRateNote:'Leave blank to use the pan\'s typical rate. A custom pan boils about 2.5 gal an hour a square foot.',
  evRate:'Boils', evEff:'Per square foot', evBoilT:'Boil time', evBoilTime:'Takes about', evSyrup:'Makes',
  evFuelCost:'Cost a {u}', evFuelNeed:'Fuel', evFuelSpend:'Fuel cost', evForSap:'For {v} {u} of sap.',
  evTrueT:'What a gallon costs you', evLaborH:'Hours this season', evLaborR:'Labor rate', evSpouts:'Spouts and tubing', evBottles:'Bottles', evFilters:'Filters', evOther:'Other',
  evFuelW:'Fuel', evLaborW:'Labor', evSuppliesW:'Supplies', evCostPer:'Cost a {u}', evCostNote:'For {s} {u} of syrup from {p} {u} of sap.',
  evRetailT:'Retail price', evRetailP:'What to charge for each bottle at your margin.', evMargin:'Margin', evYourCost:'Your cost a {u}',
  evYourCostNote:'Leave blank to use the cost above.', evBottle:'Bottle', evCostW:'Cost', evPriceW:'Price', evProfitW:'Profit',
  evBenchT:'Bulk prices by grade', evBenchNote:'USDA bulk benchmarks, about 2024.',
  // Finishing
  fiLede:'Grades, canning temperature and maple candy, set to your boiling point.',
  fiDrawAt:'Draw off at {f}°F ({c}°C)', fiDrawSub:'Water boils at {bp}°F here. Change it on Draw off.',
  fiGradesT:'Grades', fiLight:'Light {l}', fgNote1:'Very mild, early season', fgNote2:'Classic maple', fgNote3:'Strong, late season', fgNote4:'Intense, very late season',
  fiLegal:'Legal density', fiLegalV:'66.0 to 68.9% Brix', fiWeight:'Weight', fiWeightV:'About 11.65 lb a gallon at 66% Brix',
  fiCanT:'Canning and bottling', fiCanBetween:'Can between', fiCanC:'82 to 88°C',
  fiWhyRange:'Above 180°F the syrup sterilizes the bottle and seals it. Below 190°F no new niter forms and it doesn\'t get too thick.', fiAbove180:'Above 180°F', fiAbove180V:'Sterilizes and seals', fiBelow190:'Below 190°F', fiBelow190V:'No new niter, no over-thick syrup',
  fiCan1T:'Check density first', fiCan1P:'Make sure it is 66.0 to 68.9% Brix before you can. Hot syrup reads differently, so use the hydrometer fix.',
  fiCan2T:'Heat slowly, stir gently', fiCan2P:'Bring it back up on low to medium heat. Don\'t boil it hard or it thickens and makes new niter.',
  fiCan3T:'Fill hot, cap right away', fiCan3P:'Fill to a quarter inch from the top, cap it, and lay it on its side or upside down for a minute or two to sterilize the lid. Stand it up to cool.',
  fiCan4T:'Glass or plastic', fiCan4P:'Glass holds heat and shows the color. Food grade HDPE jugs are fine for short storage. Skip thin plastic that bends when hot.',
  fiCan5T:'Shelf life', fiCan5P:'Canned right, it keeps 1 to 4 years unopened. Once open, keep it cold and use it within a year. If mold shows, heat to 180°F or more, filter and can again.',
  fiYield:'250 mL is about 0.066 gal, 500 mL 0.132, 1 L 0.264, 1 qt 0.25, ½ gal 0.5.',
  fiCandyT:'Maple candy', fiCandyP:'Set from water boiling at {bp}°F.', fiBpPlus:'Boiling point + {o}°F.',
  candy_cream:'Maple cream', candy_cream_d:'Cool to about 70°F, then stir until thick and spreadable.',
  candy_taffy:'Maple taffy', candy_taffy_d:'Pour on packed snow or ice and roll it up while warm.',
  candy_molded:'Molded candy', candy_molded_d:'Cool to about 160°F, stir until it starts to grain, pour into molds fast.',
  candy_sugar:'Maple sugar', candy_sugar_d:'Stir hard as it cools until it is dry and granulated.',
  fiMoldT:'Molded candy, step by step',
  mold1T:'Heat to {t}°F.', mold1P:'Use a heavy pot. It foams up a lot.', mold2T:'Take it off the heat.', mold2P:'Right away, and don\'t stir yet.',
  mold3T:'Let it cool to about 160°F.', mold3P:'Stirring too early makes it grainy.', mold4T:'Stir hard.', mold4P:'It lightens and thickens fast.',
  mold5T:'Pour into molds.', mold5P:'Have them ready. It sets quickly.', mold6T:'Let it set.', mold6P:'5 to 10 minutes, then pop them out. Keep them cool and dry.',
  fiHydroSub:'Correct a hot hydrometer reading',
  // DE extras
  deHeadsT:'The first pour will be cloudy', deHeadsP:'That is normal while the DE builds a cake on the plates. Run it back into the pot until it comes out clear.',
  deTroubleT:'If something goes wrong',
  deT1T:'Still cloudy after a few cups', deT1P:'The cake has not formed yet. Keep running it back. If it is still cloudy after a quart, stir in another quarter cup of DE.',
  deT2T:'Pressure climbing fast', deT2P:'The plates are loading up, common with dark syrup. Stop at 40 PSI, rinse, and use 25 to 50% more DE next batch.',
  deT3T:'Nothing coming out', deT3P:'Check the valves are open. At 40 PSI or more the plates are full. Stop, take it apart, rinse and reload.',
  deT4T:'Syrup tastes of DE', deT4P:'Too much DE. Halve it next time, and use food grade filter DE, never pool DE.',
  // Break-even
  bevLede:'What your syrup has to bring in to pay for the season, and how a bad, average or great year lands.',
  bevFuel:'Fuel for the season', bevPrice:'Syrup price a {u}', bevSupplies:'Supplies and other', bevLabor:'Labor',
  bevHobby:'Hobby', bevPaid:'Count labor', bevHours:'Hours a season',
  bevEmptyT:'Enter your costs', bevEmptyP:'Fuel, supplies and labor, and the break-even shows here.',
  bevPoint:'You break even at', bevTotalSyrup:'Syrup to sell', bevSeasonCost:'Season cost', bevInclLabor:'Labor in that',
  bevScenT:'How a season lands', bev_bad:'Bad year', bev_avg:'Average year', bev_great:'Great year',
  bevScenSub:'{y} {u} a tap, {t} {u} of syrup, {w}', bevAbove:'above break-even', bevBelow:'below break-even',
  bevMarkerNote:'The white mark is your break-even per tap.',
  bevHighT:'Break-even is above a great year', bevHighP:'You need {v} {u} a tap. Cut costs or raise your price.',
  // Recap detail
  rdTitle:'{y} season recap', rdLede:'The numbers behind your score, where the gap is, and a replay of the season.',
  rpBtnW:'Replay', shareCard:'Share card', rpNeed:'Replay opens once 3 dated entries are logged.', rpNeedNone:'Replay and the share card open once you log this season.',
  rdNumbers:'The numbers', rdRatio:'Sap to syrup', rdTheory:'{r}:1 in theory', rdLength:'Season length', rdNoDates:'No dated entries',
  rdBest:'Best run', rdRo:'Through the RO', rdUtil:'{p}% of what you boiled', rdBrixRange:'{a} to {b}%', rdEntries:'Entries', rdEntriesSub:'{s} sap, {y} syrup',
  rdYoy:'Against {y}', rdYoySub:'{a} to {b} {u}',
  rdScoreT:'Score breakdown', copyScore:'Copy score', copied:'Copied', scoreShareText:'My {y} maple season scored {s}/100 ({g}) on SweetRun. sweetrun.app',
  sr_yield:'Yield a tap', sr_eff:'Evaporation', sr_fuel:'Fuel', sr_data:'Data logged',
  srs_yield_top:'{y} {u} of syrup a tap, top of {a} to {b} for {m}', srs_yield_in:'{y} {u} of syrup a tap, inside {a} to {b} for {m}',
  srs_yield_below:'{y} {u} a tap, under {a} for {m}', srs_eff:'{a}:1 actual against {t}:1 in theory', srs_fuel:'{f} {fu} a {w} of syrup, {b} expected', litreW:'litre', gallonW:'gallon',
  srs_data:'{n} of 4 things logged',
  rdConvT:'Conversion', rdActual:'Actual', rdRule86:'Rule of 86', rdVsTheory:'Against theory',
  rdConvHigh:'Your ratio is {p}% over theory. Check for foam loss, leaks, or syrup drawn thin.',
  rdOpName:'Operation name', rdOpPh:'Maple Hollow Sugarhouse', rdOpNote:'Printed on your share card. Stays on this device.',
  gapT:'Yield gap', gapMade:'You made', gapBench:'Benchmark', gapGap:'Gap', gapSurplus:'Over by',
  gapBenchNote:'That is {a} to {b} {u} a tap for {m}.', gapYours:'Your yield', gapCosts:'That gap costs about', gapAtPrice:'at {p} a {u}',
  gapCausesT:'Why, and what to do',
  gc_lowYield:'Low yield per tap', gc_lowYield_d:'{y} {u} a tap against {a} to {b} for {m}. This is most of your gap.',
  gc_belowAvg:'Yield per tap under the middle', gc_belowAvg_d:'{y} {u} a tap is inside {a} to {b} for {m}. The middle would add {add} {u} a season.',
  gc_evapLow:'Evaporator running under par', gc_evapLow_d:'Your {r}:1 is {p}% off theory for {bx}% sap. It is taking too long to concentrate.',
  gc_evapMinor:'A little evaporation loss', gc_evapMinor_d:'{r}:1 is {p}% off theory. Small gains are there.',
  gc_considerRo:'An RO would cut boil time and fuel', gc_considerRo_d:'Taking {bx}% sap to 8% with one RO pass removes about 70% of the water before you boil.',
  gc_good:'Your operation is doing well', gc_good_d:'Yield and efficiency are at or near benchmark. Work on doing it the same way every run.',
  sev_high:'Fix first', sev_medium:'Worth doing', sev_low:'Keep an eye on', sev_good:'Looking good',
  fixMeta:'Cost {c} · Time {t}', imp_veryHigh:'Very high impact', imp_high:'High impact', imp_medium:'Medium impact',
  fix_leaks:'Check every lateral for small leaks at the tees', fix_checkValve:'Switch to check valve spouts',
  fix_freshWood:'Make sure tap holes are in fresh white wood', fix_audit5:'Gauge vacuum at 5 random taps and look for more than 2\u00a0in\u00a0Hg difference',
  fix_checkValveLow:'Put check valve spouts on your weakest laterals', fix_float:'Check the float keeps a steady level while you boil',
  fix_descale:'Clean the niter off the flue pan', fix_drawTiming:'Check draw off timing. Drawing early makes thin syrup and less of it',
  fix_floatCal:'Check the float setting and where the flue pan draws off', fix_roSingle:'A single pass RO (CDL, Leader, H2O Innovation)',
  fix_roDiy:'A home built RO, membranes and a pump', fix_document:'Write down tap spots, vacuum readings and your best run weather for next year',
  roSavT:'RO against a straight boil', roSavHours:'Boiling time', roSavWood:'Wood burned', roStraight:'Straight boil', roWith:'With your RO', roWithPre:'With RO and preheater',
  roConcNote:'{r} {u} through the RO became {c} {u} of concentrate', roNoData:'No RO logged yet. The bars show a straight boil.',
  roSavedH:'Hours saved', roSavedW:'Wood saved', roSavedC:'Cords saved', roLogNote:'Log sap through the RO to see what it saves you.',
  roInputs:'Your evaporator and RO', roInputsSub:'{e} gal/h, {b} lb of wood an hour, RO to {x}%',
  roEvapRate:'Evaporator rate', roBurn:'Wood burned', roOutBrix:'RO concentrate', roPreheater:'Preheater',
  rdPoints:'By collection point', rdPointSub:'{n} runs · {r}', rdUnassigned:'Not tagged to a point',
  rpTitleW:'{y} season replay', rpSap:'Sap, {u}', rpSyrup:'Syrup, {u}', rpDay:'Day', rpBest:'best run {v} {u}', rpFirst:'first boil', rpPeak:'peak Brix {v}%',
  rpPrevW:'Previous day', rpNextW:'Next day', rpAgain:'Play again', rpPlay:'Play', rpPause:'Pause',
  scName:'My sugarbush', scSeason:'{y} maple season', scSyrup:'Syrup', scSap:'Sap', scRatio:'Ratio', scTaps:'Taps', scSaved:'Share card saved',
  // Diagnose
  dxLede:'Where your {y} season lost syrup and what it is worth to fix, from your log and research benchmarks.',
  dxPrice:'Syrup price', dxWood:'Wood cost', dxRoBrix:'RO concentrate', dxRoBrixNote:'Leave at 0 if you have no RO.',
  dxVac:'Tap system', vac_gravity:'Gravity', vac_vac15:'15 inch vacuum', vac_high:'High vacuum, 25 inch and up', vacB_gravity:'Gravity', vacS_gravity:'no pump', vacB_vac15:'15 inch', vacS_vac15:'vacuum', vacB_high:'High vacuum', vacS_high:'25 in and up',
  dxGalNote:'The findings below work in US gallons, the unit the research benchmarks use.',
  dxNoneT:'No {y} entries yet', dxNoneP:'Log sap and syrup and the diagnosis fills in.',
  dxFindings:'What we found', dxRoi:'${v} a season', dxAction:'What to do', dxEffort:'Effort: {e}',
  dxTotal:'Total you could gain', dxTotalNote:'A yearly estimate from the findings above.',
  dxSources:'Benchmarks: UVM Proctor Maple Research Center, Cornell Maple Program, Maine Maple Producers Association, USDA NASS.',
  dx_yield_t:'Low sap yield per tap', dx_yield_s:'{ypt} gal of sap a tap, against {lo} to {hi} for {vac}.',
  dx_yield_a:'On gravity, 3/16" laterals can add 5 to 10 gal a tap with no pump. On vacuum, look for leaks, check the pump pulls its inches, and check valves and tap seals.',
  dx_yield_e:'Medium', dx_yield_p:'About ${roiV} more syrup this season',
  dx_yield_d1:'Your bush: {ypt} gal of sap a tap', dx_yield_d2:'Benchmark for {vac}: {lo} to {hi} gal of sap a tap',
  dx_yield_d3:'Gap: {gap} gal a tap across {taps} taps, {lost} gal of sap', dx_yield_d4:'At {r}:1 that is {syr} gal of syrup at ${price}, ${roiV}. Source: UVM Proctor',
  dx_yieldOk_t:'Yield per tap looks solid', dx_yieldOk_s:'{ypt} gal of sap a tap is at or above the {lo} to {hi} benchmark.',
  dx_conv_t:'More sap per gallon of syrup than expected', dx_conv_s:'{ar}:1 against {tr}:1 in theory, {off}% more sap for each gallon.',
  dx_conv_a:'Check for foam overflow, leaks, syrup drawn too thin, or volumes logged wrong.', dx_conv_e:'Low', dx_conv_p:'About {lost} gal of syrup lost, ${roiV}',
  dx_conv_d1:'Your ratio {ar}:1. Rule of 86 at {brix}% Brix is {tr}:1', dx_conv_d2:'Extra sap used: {excess} gal',
  dx_conv_d3:'About {lost} gal of syrup at ${price}, ${roiV}', dx_conv_d4:'Source: Cornell Maple Program',
  dx_convBad_t:'Sap and syrup totals disagree', dx_convBad_s:'{ar}:1 is under the {floor}:1 floor the sugar in sap allows. This is a logging problem, not a boiling problem.',
  dx_convBad_a:'Look in Log history for sap logged as syrup, or a reading with an extra digit. Scores wait until these agree.', dx_convBad_e:'Low',
  dx_convBad_d1:'Your ratio {ar}:1. The floor is about {floor}:1, sap at {maxB}% Brix', dx_convBad_d2:'Rule of 86 at {brix}% Brix would be {tr}:1',
  dx_convBad_d3:'Yield, efficiency and fuel scores are held back until then.',
  dx_convOk_t:'Sap to syrup ratio is on target', dx_convOk_s:'{ar}:1 against {tr}:1 in theory, {off}% apart.',
  dx_roLow_t:'The RO is not keeping up', dx_roLow_s:'Only {pct}% of the sap you boiled went through the RO first. Aim for over 90%.',
  dx_roLow_a:'Run all your sap through the RO before it reaches the evaporator. It is the biggest fuel saver you own.', dx_roLow_e:'Low',
  dx_roLow_p:'About {cords} cords of wood saved, ${save}', dx_roLow_d1:'Through the RO {ro} gal, boiled {ev} gal', dx_roLow_d2:'{gap} gal boiled without the RO',
  dx_roLow_d3:'An RO cuts boiling by 60 to 75%', dx_roLow_d4:'Wood at ${wood} a cord. Source: UVM Proctor',
  dx_roOk_t:'RO use is strong', dx_roOk_s:'{pct}% of the sap you boiled went through the RO first.',
  dx_roNone_t:'No RO in use', dx_roNone_s:'You boiled {ev} gal with no RO. That is a lot of wood.',
  dx_roNone_a:'A small RO, about 150 gal/h, pays for itself in 1 to 3 seasons above 500 taps. Rent one before you buy.', dx_roNone_e:'High',
  dx_roNone_p:'About ${save} a season in wood at your volume', dx_roNone_d1:'{ev} gal boiled with no RO', dx_roNone_d2:'An RO cuts boiling by 60 to 75%',
  dx_roNone_d3:'About {cords} cords at ${wood}, ${save}. Source: Maine Maple Producers',
  dx_roBrixLow_t:'RO concentrate is thin', dx_roBrixLow_s:'{rb}% Brix out of the RO. Aim for 8 to 12%.',
  dx_roBrixLow_a:'Run a second pass, raise the pressure or slow the feed. If it stays low, wash or replace the membranes.', dx_roBrixLow_e:'Low',
  dx_roBrixLow_p:'Doubling the concentrate halves boiling time and fuel', dx_roBrixLow_d1:'Now {rb}% Brix, target 8 to 12%',
  dx_roBrixLow_d2:'Two passes to 12 to 16% before boiling is best', dx_roBrixLow_d3:'Source: Cornell Maple Program',
  dx_roBrixOk_t:'RO concentrate is good', dx_roBrixOk_s:'{rb}% Brix is solid. Over 10% boils very efficiently.',
  dx_vacuum_t:'Gravity lines: room to add vacuum', dx_vacuum_s:'{taps} taps on gravity. 3/16" natural vacuum could add ${roiV} a season.',
  dx_vacuum_a:'Switch laterals to 3/16" tubing for 12 to 15\u00a0in\u00a0Hg of natural vacuum. No pump, no power. The best upgrade for a gravity bush.', dx_vacuum_e:'Medium',
  dx_vacuum_p:'About ${roiV} a season from the extra sap', dx_vacuum_d1:'3/16" laterals make 12 to 15\u00a0in\u00a0Hg by siphon', dx_vacuum_d2:'Typical gain: 6 to 10 gal a tap over plain gravity',
  dx_vacuum_d3:'{taps} taps at 8 gal is {addl} gal of sap, {syr} gal of syrup', dx_vacuum_d4:'Source: UVM Proctor 3/16" tubing research',
  dx_grades_t:'{bad} of {n} lines have flow problems', dx_grades_s:'The worst stretch is {worst}% grade. Lines need at least 1%.',
  dx_grades_a:'Reroute flat or uphill stretches, add a releaser partway, or add vacuum.', dx_grades_e:'High', dx_grades_p:'Good grade stops sap pooling and souring',
  dx_grades_d1:'Lines checked {n}, with problems {bad}', dx_grades_d2:'At least 1% grade, about 1 ft of drop every 100 ft', dx_grades_d3:'2 to 5% is best',
  dx_grades_d4:'Source: UVM Extension tubing guide',
  dx_gradesOk_t:'Line grades look good', dx_gradesOk_s:'All {n} lines have enough grade. The lowest stretch is {worst}%.',
  dx_yoyDown_t:'Sap down {chg}% from last year', dx_yoyDown_s:'{now} {u} this season against {prev} {u} last season.',
  dx_yoyDown_a:'Look at your tapping date, how often you collect, downtime and the weather. Late tapping cuts yield.', dx_yoyDown_e:'Low, worth a look',
  dx_yoyDown_d1:'Sap {prev} to {now} {u}, {sign}{chg}%', dx_yoyDown_d2:'Syrup {syPrev} to {syNow} {u}, {sSign}{sChg}%',
  dx_yoyDown_d3:'Swings over 20% usually mean timing, weather or equipment', dx_yoyDown_d4:'Seasons normally vary by about 15%',
  dx_yoyUp_t:'Sap {sign}{chg}% on last year', dx_yoyUp_s:'{now} {u} this season against {prev} {u} last season.',
  dx_yoyUp_d1:'Sap {prev} to {now} {u}, {sign}{chg}%', dx_yoyUp_d2:'Syrup {syPrev} to {syNow} {u}, {sSign}{sChg}%',
  dx_yoyUp_d3:'Swings over 20% usually mean timing, weather or equipment', dx_yoyUp_d4:'Seasons normally vary by about 15%',
  dx_brixDown_t:'Sap Brix is falling. The season may be ending', dx_brixDown_s:'Your last three readings average {late}% against {avg}% for the season.',
  dx_brixDown_a:'When Brix stays under 1.5 to 1.8% and nights stop freezing, pull the taps to spare the trees.', dx_brixDown_e:'Low',
  dx_brixDown_p:'Pulling at the right time protects next year\'s yield', dx_brixDown_d1:'Season average {avg}%, last three {late}%',
  dx_brixDown_d2:'Brix falls as the trees wake up', dx_brixDown_d3:'Buddy sap makes off flavored syrup. Source: Maine Maple Producers',
  dx_brixOk_t:'Sap Brix is holding', dx_brixOk_s:'{n} readings, averaging {avg}%. No drop yet.',
  dx_labor_t:'Labor is a big share of revenue', dx_labor_s:'About {hrs} h at ${lr} an hour is ${cost}, {pct}% of about ${rev} in syrup.',
  dx_labor_a:'Look at bulk sales, shared equipment, or vacuum that cuts collection trips.', dx_labor_e:'Medium', dx_labor_p:'Under 30% of revenue is a common target',
  dx_labor_d1:'Collections logged {runs}, syrup {syr} gal', dx_labor_d2:'Labor about {hrs} h at ${lr}, ${cost}', dx_labor_d3:'Revenue about {syr} gal at ${price}, ${rev}',
  dx_labor_d4:'Labor is {pct}% of revenue, target under 30%. Source: USDA NASS',
  dx_laborOk_t:'Labor cost looks fine', dx_laborOk_s:'About {hrs} h at ${lr} an hour is {pct}% of revenue.',
  insT:'Season insights',
  ins_yieldStrong:'Strong yield per tap', ins_yieldStrong_b:'{y} {su} of syrup a tap, above the {lo} to {hi} benchmark.', ins_yieldStrong_a:'Write down your tap spots and vacuum settings and do the same next year.',
  ins_yieldAvg:'Average yield per tap', ins_yieldAvg_b:'{y} {su} of syrup a tap, near the industry average.', ins_yieldAvg_a:'Switch to check valve spouts and look for vacuum leaks at every lateral connection.',
  ins_yieldLow:'Yield per tap is under average', ins_yieldLow_b:'{y} {su} of syrup a tap is under the {lo} benchmark.', ins_yieldLow_a:'Check spout condition, tap into fresh white wood, and test vacuum at the tree.',
  ins_effTop:'Excellent evaporation', ins_effTop_b:'{r}:1, {e}% of the best possible for {bx}% sap.', ins_effTop_a:'Write down your evaporator setup. This is benchmark boiling.',
  ins_effGood:'Good evaporation', ins_effGood_b:'{r}:1, {e}% of theory.', ins_effGood_a:'Check the float level and the flue pan draw off. Small changes can win back 5 to 10%.',
  ins_effLow:'Evaporation needs a look', ins_effLow_b:'{r}:1 is {g}% under theory for {bx}% sap.', ins_effLow_a:'Check the flue pan flow, the evaporator level and draw off timing at the finisher.',
  ins_fuelGood:'Fuel efficient', ins_fuelGood_b:'{f} {u} a {w} of syrup, under the {b} expected.', ins_fuelGood_a:'Your evaporator is dialed in. A preheater is the next gain.',
  ins_fuelHigh:'Using a lot of fuel', ins_fuelHigh_b:'{f} {u} a {w} of syrup, over the {b} expected.', ins_fuelHigh_a:'An RO to 8 to 10% Brix could cut fuel by 60 to 70%.',
  ins_roHelps:'The RO is pulling its weight', ins_roHelps_b:'{p}% of your sap went through the RO.', ins_roHelps_a:'Push the concentrate to 10 to 12% Brix if your membranes allow, for the most fuel saved.',
  // Guide
  kbLede:'{n} answers from maple research, searchable and sorted by topic.', kbAsk:'Ask about maple production', kbAskPh:'Why is my syrup cloudy?',
  kbTry:'Try one', sugSap:'Why does sap flow?', sugRo:'How does RO work?', sugVac:'Best vacuum level', sugNiter:'Niter in syrup', sugYield:'Yield per tap', sugOff:'Off flavors',
  kbTopics:'Topics', kbArticles:'{n} answers', kbNoneT:'Nothing found', kbNoneP:'Try other words, or pick a topic.', kbTip:'Tip', kbSource:'Source: {s}',
  kbMonthT:'This month', kbTools:'Tools', kbDxSub:'Where the season lost syrup', kbRecapSub:'Score, replay and share card',
  kbSources:'From UVM Proctor, the Cornell Maple Program and other maple research.',
  cat_all:'All', cat_biology:'Biology', cat_tapping:'Tapping', cat_vacuum:'Vacuum', cat_ro:'RO', cat_evaporation:'Evaporation', cat_finishing:'Finishing',
  cat_weather:'Weather', cat_tree_health:'Tree health', cat_business:'Business', cat_lines:'Lines', cat_troubleshooting:'Troubleshooting',
  kbMonth0:'Go over every fitting and replace cracked tubing before the deep cold.', kbMonth1:'Sharpen drill bits and sort spouts. Fresh holes drill cleaner and seal better.',
  kbMonth2:'Peak season. Check vacuum at the pump every day. Losing 2\u00a0in\u00a0Hg cuts yield.', kbMonth3:'Watch the sap color. Buddy sap comes when the trees bud. Stop when it does.',
  kbMonth4:'Pull taps promptly. Spouts left in damage the wood and cut next year\'s yield.', kbMonth5:'Service the RO membranes now. Flush and store them in a food safe preservative.',
  kbMonth6:'Walk the mainline for sun damage and chewed tubing. Replace cracked sections.', kbMonth7:'A good time to scout new trees. Healthy maples 10 inches and up.',
  kbMonth8:'Put in new tubing runs before the leaves fall. Check the grade on every mainline.', kbMonth9:'Blow out every line with compressed air before the first hard freeze.',
  kbMonth10:'Order supplies early. Spouts and tubing sell out by February.', kbMonth11:'Look back over this season\'s log and set yield targets for next year.',
  // Season Pass
  passActiveP:'Your Season Pass is active through {d}. Thank you for backing a one person project.',
  passEndedP:'Your Season Trial has ended. Your data is safe, and viewing and export always work, but new entries need a pass.',
  passTrialP:'You are on a free Season Trial, {n} days left. It never ends before you have had 3 real sap days. Everything is unlocked.',
  passBuy:'Get a Season Pass, $49.99 a year', passHave:'Have a pass key?', passPh:'Paste your Season Pass key', passActivate:'Activate',
  passBad:'That key doesn\'t look right. Check for missing characters, or email hello@sweetrun.app and I\'ll sort it out.',
  passExpired:'This Season Pass expired {d}. Get a new one above.', passOk:'Season Pass active through {d}. Boil on.',
  emailAsk:'Email me (optional)', emailWhy:'Sap season tips, and a heads up before your trial ends.', emailPh:'you@sugarbush.com', emailBtn:'Keep me posted',
  emailBad:'That email doesn\'t look complete.', emailOk:'Got it. You\'re on the list.', emailFail:'That didn\'t go through. Try again in a bit.',
  // First-season setup
  wzT0:'Your trees', wzT1:'Your system', wzT2:'Your evaporator', wzT3:'Costs and price', wzT4:'Your season plan', wzStep:'Step {n} of 5',
  wz0P:'Start with your trees. This sets your real production potential.', wzTrees:'Maple trees you tap', wzNeedTrees:'Enter how many trees you tap to go on.', wzTrunk:'Average trunk at chest height',
  wzSmall:'Under 10 in', wzSmallS:'1 tap a tree', wzMed:'10 to 18 in', wzMedS:'1 or 2 taps', wzLarge:'Over 18 in', wzLargeS:'2 or 3 taps',
  wz1P:'Your system is the biggest lever on how much sap each tap gives.', wzSystem:'Tap system', wzGravity:'Gravity', wzVacuum:'Vacuum',
  wzCollect:'Collection', wzBuckets:'Buckets', wzBucketsS:'By hand', wzMainline:'Mainline', wzMainlineS:'Runs to a tank',
  wz2P:'Your evaporator sets how many boils the season takes.', wzHasEvap:'Do you have an evaporator?', wzYes:'Yes', wzYesS:'Ready to boil', wzNo:'Not yet', wzNoS:'Planning ahead',
  wz3P:'Two numbers that show what the season is worth.', wzFuelCost:'Fuel for the season', wzFuelCostNote:'The whole season, for break-even. Price a cord or a gallon is on the Evaporator screen.',
  wzPrice:'Syrup price', wzPriceNote:'Bulk maple usually sells for $35 to $70 a gallon.',
  wzRecTaps:'Taps', wzSyrupRange:'Syrup expected', wzSapEst:'Sap expected', wzRevenue:'Season revenue', wzAvgYear:'in an average year', wzSessions:'Boils', wzCords:'Cords of wood',
  wzChecklist:'Season checklist',
  wzc1T:'February, prep.', wzc1P:'Check equipment, bits, spouts and lines. Order supplies now.',
  wzc2T:'Late February, watch.', wzc2P:'Look for 40°F days after freezing nights in the 10-day forecast.',
  wzc3T:'First run.', wzc3P:'Tap when the pattern shows up. Early sap is your best.',
  wzc4T:'During the season.', wzc4P:'Collect within 24 to 48 hours, keep it cold if you can\'t boil the same day, and log every run.',
  wzc5T:'Late season.', wzc5P:'Watch for buddy sap, cloudy with an off taste. Pull taps when the buds swell.',
  wzc6T:'After the season.', wzc6P:'Clean the lines, store things dry, and check your Recap.',
  wzNoTreesT:'Go back and enter your trees', wzNoTreesP:'Your season plan needs a tree count.', wzFinish:'Save plan', wzRange:'{a} to {b} {u}',
  // Import
  impTitle:'Import season data', impSource:'Where it comes from', impPaste:'Or paste rows',
  imp_sugarcalc_pdf:'SugarCalc PDF', imp_sugarcalc_pdf_h:'Any SugarCalc Season Report PDF. SweetRun reads it for you.',
  imp_sapspy:'SapSpy CSV', imp_sapspy_h:'In SapSpy: Settings, Data Export, CSV.', imp_saptrac:'SapTrac CSV', imp_saptrac_h:'In SapTrac: File, Export, Sap Log CSV.',
  imp_generic:'Any CSV', imp_generic_h:'Columns named date, sap and syrup.', imp_manual:'Paste rows', imp_manual_h:'Comma separated: date, sap, syrup.',
  impPickPdf:'Pick a PDF', impPickCsv:'Pick a CSV file', impPdfFail:'Couldn\'t read that PDF. Try again, or export a CSV instead.',
  impNeedRows:'Needs a header row and at least one row of numbers.', impNoCols:'Couldn\'t find sap or syrup columns. Name them sap and syrup.',
  impNoRows:'No rows with numbers in them.', impNoPdfRows:'No log entries found. Is this a SugarCalc Season Report?',
  impReady:'{n} rows ready for {y}', impRo:'Through the RO', impEvap:'Into the evaporator', impSkip:'{n} already in your log will be skipped.',
  impUnitNote:'Numbers come in as {u}, your unit now.', impGo:'Import {n} entries', impDone:'Imported {n} entries',
});
