// ─── Run Sheet strings, Phases 7-8: Bush, Pumps, Watch, wide layouts ────────
// English complete; French for the most-seen words (titles, statuses, buttons).
// rt() falls back to English for the rest; the list is in fr-todo.txt.
// No em or en dashes; numbers arrive formatted; "Sap's running!" is the one
// exclamation (the approved prototype's banner).
Object.assign(RS_TR.en, {
  // Bush chrome
  bushMap:'Bush map', bushCountsT:'{t} taps · {l} lines', bushMapAria:'Bush map with {t} trees and {l} mainlines. Use the list beside it to reach each line.',
  bushPanel:'Lines, tanks and pumps', bushLayers:'Bush layers', addToMap:'Add to the map', gpsStart:'Show where I am', gpsStop:'Stop following me',
  zoomIn:'Zoom in', zoomOut:'Zoom out', watchBush:'Watch the bush', mapTools:'Map tools', mapToolsS:'Draw a mainline, import a boundary, save the map offline',
  lyTrees:'Trees', lyLaterals:'Laterals', lyLines:'Lines', lyVacuum:'Vacuum', lyBrix:'Brix', lyPumps:'Pumps', lyTanks:'Tanks', lyProperty:'Property line',
  lyTreesS:'Every tapped tree as a dot', lyLateralsS:'Each tree to its mainline', lyLinesS:'Mainlines with their letter plates',
  lyVacuumS:'Lines coloured by their latest end reading, leak suspects in red', lyBrixS:'Brix readings taken at a tree', lyPumpsS:'Pumps on the map, turning while they run',
  lyTanksS:'Tanks with their level', lyPropertyS:'The boundary you imported', layersNote:'Your layer choice is kept on this device.',
  baseMap:'Base map', baseSat:'Satellite', baseSatT:'Satellite + terrain', baseTopo:'Topo', baseStreet:'Street',
  mapLoadT:'The map could not load', mapLoadP:'The map library did not arrive. Check your connection and try again. Your trees and lines are safe on this device.',
  tilesDown:"Imagery isn't loading. You may be offline or the map service is down. Your trees and lines still show.",
  bushEmptyT:"Your bush isn't on the map yet", bushEmptyP:'Stand at a tapped tree and add it where you are, or import your property line to get your bearings.',
  addTreeHere:'Add a tree where I am', leakSuspectW:'Leak suspect', noReadingW:'no reading', lineAria:'{n}, {v}',
  gpsFinding:'Finding you…', gpsAcc:'GPS ± {a} m', gpsAccShort:'GPS ± {a} m', gpsDenied:'Location is turned off for SweetRun.', gpsLost:'Lost the GPS signal. Try in the open.',
  gpsNone:'This device has no GPS.', gpsCanopy:'GPS under canopy is often 5 to 15 m off. The accuracy is saved with the pin.',
  pinAdded:'{n} added', pinAddedAcc:'{n} added, ± {a} m', tapToAdd:'Tap the map to add a {k}', doneW:'Done', undoW:'Undo', cancelW:'Cancel',
  drawHint:'Tap points along {n}, top of the line first, down to the tank', drawPts:'{n} points', saveLine:'Save line', lineDrawn:'Line saved',
  whatAdd:'What are you adding?', onWhichLine:'On which mainline?', noLineW:'None yet', addAtGps:'Add it where I am', addByTap:'Tap the map to place it',
  typeCoords:'Type coordinates', latW:'Latitude', lonW:'Longitude', addAtCoords:'Add at these coordinates', coordsBad:'Use decimal degrees, like 44.5412 and -69.6203.',
  pinK_tree:'Tree', pinK_tank:'Tank', pinK_pump:'Pump', pinK_sugarhouse:'Sugarhouse', pinK_marker:'Waypoint', pinK_junction:'Junction',
  // Map tools
  drawAMainline:'Draw a mainline', drawAMainlineP:'Pick a line, then tap points along it on the map. A drawn line replaces the one drawn through its trees.',
  newMainline:'New mainline', importBoundary:'Import a boundary', importBoundaryP:'A KML, GPX or GeoJSON file of your property line. It is saved and goes into your backup.',
  chooseFile:'Choose a file', impBad:"Couldn't read that file. SweetRun takes .kml, .gpx and .geojson.", impNone:'That file had no boundary lines to draw.',
  impOk:'{n} boundaries drawn and saved.', impOk1:'Boundary drawn and saved.', clearBoundary:'Remove the boundary', tapAgainClear:'Tap again to remove it', boundaryCleared:'Boundary removed',
  offlineP:'Saves the imagery for what is on screen now, one zoom step either side, so the map works with no signal.', saveArea:'Save this area offline',
  tilesSaving:'Saving {d} of {t}', tilesOk:'{n} tiles saved. This area works offline now.', tilesNone:'0 of {n} tiles saved. No connection. Try again when you have signal.',
  tilesSome:'{s} of {n} tiles saved. Weak signal. Try again to fill the gaps.', tilesTooMany:'That is {n} tiles. Zoom in closer and try again.', tilesZoomOut:'Nothing to save at this zoom. Zoom out a step.',
  // Tree detail
  elevation:'Elevation', placedBy:'Placed', placedByHand:'By hand on the map', h_excellent:'Excellent', h_good:'Good', h_fair:'Fair', h_poor:'Poor', h_dead:'Dead',
  brixHere:'Brix at this tree', noBrixHere:'No reading at this tree yet.', logBrixHere:'Log Brix at this tree', saveBrixV:'Save {v}% here',
  brixSaved:'{v}% saved at {n}', brixAtTree:'At tree {n}', deleteTree:'Delete this tree', treeDeleted:'Tree deleted',
  // Line detail
  readAgo:'Read {a}, {t}', readAgoShort:'Read {a}', agoNow:'just now', agoMin:'{n} min ago', agoH:'{n} h ago', agoD1:'yesterday', agoD:'{n} days ago',
  noReadingYet:'No reading yet', noReadingShort:'No reading', latestW:'Latest', lengthW:'Length', drawnW:'Drawn', lastChecked:'Last checked', neverW:'Never', servedBy:'Vacuum from',
  drawnByYou:'By you', drawnTrees:'Along its {n} trees, into the tank', drawnTreesElev:'Along its {n} trees, highest first', notDrawn:'Not yet: assign trees or draw it',
  tapsSetV:'{n} (set by you)', leakVerdict:'Leak suspect. {d} in under its recent baseline of {b} in.', holdingVerdict:'Holding. {d} in under its recent baseline of {b} in.',
  oneReadingVerdict:'One reading so far. The leak check needs a second one to compare.', noReadingVerdict:'No vacuum reading at the end of this line yet.',
  leakRuleNote:'Leak rule: {l} in or more under the median of its readings in the {d} days before. That is a default you can change in Sugar Shack.',
  logVacuum:'Log a vacuum reading', markChecked:'Mark checked', checkedSaved:'{n} marked checked', watchLine:'Watch this line', openOnBush:'Show on the Bush map',
  editLine:'Name, taps and drawing', tapsOnLine:'Taps on this line', tapsOnLineNote:'Leave blank to count the taps on its trees ({n}).', drawThisLine:'Draw this line', redrawLine:'Draw it again',
  vacAtEnd:'Vacuum at the end of {n}', vacTrendAria:'{n}, the last {k} vacuum readings', kindW:'Kind', noteW:'Note', levelW:'Level', coordsW:'Coordinates',
  openTank:'Open {n}', openPump:'Open {n}', trackTank:'Track the level of this tank', trackPump:'Track this pump',
  noLinesBush:'Add trees to a mainline on the Bush map, or draw one from Map tools.',
  // Pump center
  pumpsLedeEmpty:'Pumps, tanks and the vacuum at your line ends, in one place.', pumpsNeed1:'1 thing needs you. The rest is quiet.', pumpsNeed:'{n} things need you.',
  pumpsAllGood:'Nothing needs you right now.', pumpsEmptyT2:'Add your first pump', readouts:'Readouts',
  pumpsEmptyP2:'Your vacuum pump, transfer pump, RO and generator. Mark them running or stopped, and SweetRun keeps the runtime, fuel and service for you.',
  pumpsHonest:'No sensors needed. Everything here comes from what you mark and log, with the time you did it.',
  lineEnd:'{n} end', leakSuspectD:'Leak suspect · {d} in down', tankPctRead:'{p}% · read {a}', noLevelYet:'No level logged yet', freezePrep:'Freeze prep',
  noForecastShort:'No forecast', lowTonightV:'{v}°F tonight', noFreezeV:'Low {v}°F, no freeze', ofN:'of {n}', byJob:'By job', vacAndLeaks:'Vacuum and leaks',
  allLinesW:'All lines', leaksOnV:'Leak suspect on {n}', allHoldingOrNone:'Line end readings and the leak rule', freezeRowS:'{d} of {t} done for tonight', freezeRowNone:'Add a pump to get a checklist',
  transferTimeS:'How long a haul takes, on Equipment', addPump:'Add a pump', addTank:'Add a tank', stRunning:'Running', stStopped:'Stopped',
  stStoppedSince:'Stopped since {t}', stFaultSince:'Fault since {t}', sinceT:'since {t}', hToday:'h today', noFuelShort:'No fuel logged',
  last7:'Line ends, last 7 days', newestRead:'Newest read {a}', noVacT:'No vacuum readings yet', noVacP:'Log the vacuum at the far end of a line from its detail. Two readings start the leak check.',
  noVac7:'No readings in the last 7 days.', vacChartAria:'Vacuum at the end of {n} lines over the last 7 days', nowW:'Now',
  readWhen:'When did you read it?', justNow:'Just now', minAgo:'{n} min ago', hAgo1:'1 h ago', hAgoN:'{n} h ago', readingSaved:'{v} {u} saved',
  saveReading:'Save the reading', saveReadingV:'Save {v} {u}',
  // Add or change a pump
  pumpKind:'Kind of pump', kind_vacuum:'Vacuum', kind_transfer:'Transfer', kind_ro:'RO', kind_generator:'Generator',
  kindName_vacuum:'Vacuum pump', kindName_transfer:'Transfer pump', kindName_ro:'RO', kindName_generator:'Generator',
  whereOpt:'Where it is (optional)', wherePh:'Pumphouse', onTheMapW:'On the map', notOnMap:'Not on the map', linesServed:'Lines it pulls on', tankLinked:'Tank',
  noneW:'None', fuelTank:'Fuel tank, {u}', burnRate:'Burns, {u} an hour', perH:'{u}/h', offW:'off', serviceEvery:'Service reminder every (optional)', serviceNote:'Leave it blank for no reminder. Hours count while it is marked running.',
  genDefaults:'Blank uses {c} {u} and {b} {u} an hour, a small portable generator. Check your manual.', addNamed:'Add {n}', changePump:'Change this pump',
  pumpAdded:'{n} added', pumpSaved:'{n} saved', roRate:'RO rate, {u} an hour', roRateNote:'Used for "Run the RO" timing from your tank level.',
  // Pump detail
  pumpGoneT:'That pump is gone', pumpGoneP:'It was removed, or this link is from another device.', markRunning:'Mark it running', markStopped:'Mark it stopped',
  runningAgain:"It's running again", reportFault:'Report a fault', removePump:'Remove this pump', pumpRemoved:'{n} removed',
  st_running_saved:'{n} running. The clock is going.', st_stopped_saved:'{n} stopped', st_fault_saved:'Fault saved for {n}',
  statusHonest:'You set this by hand. SweetRun counts the runtime from the time you give it.', runtimeW:'Runtime', todayWordC:'Today', thisSeasonC:'This season',
  countingNow:'counting now', notRunning:'not running', sinceJan1:'since January 1', serviceDue:'Service', overdueBy:'Overdue by {h} h', inHours:'Due in {h} h',
  sinceService:'{h} h since the last service', fuelW:'Fuel', fuelLeft:'Fuel left', fillSoon:'Fill it soon', fineW:'Fine', ofCap:' of {c} {u}',
  burning:'Burning', perHourV:'{v} {u} an hour', runsFor:'Runs for', dryNear:'Runs dry near', whenRunning:'Only counts while running', lastFill:'Last filled',
  fuelHow:'Worked out from your last fill and the hours it has run since, at the burn rate you set.', noFuelLogged:'Log a fill-up to start the fuel clock.',
  logFuel:'Log fuel', releaserVac:'Vacuum at the pump', logReleaser:'Log the pump vacuum', releaserOf:'Vacuum at {n}', serviceParts:'Service and parts',
  serviceW:'Service', atHours:'at {h} h', noServiceT:'No service logged', noServiceP:'Oil changes, filters, belts. The hours are counted from the last one.',
  logService:'Log a service', historyW:'History', noHistory:'Nothing yet.', ev_running:'Marked running', ev_stopped:'Marked stopped', ev_fault:'Fault reported',
  evFuel:'Fuel to {v} {u}', evService:'{w}', markRunningN:'Mark {n} running', startedW:'It started', runClockNote:'The runtime clock counts from this time and keeps counting until you mark it stopped.',
  startClock:'Start the clock', faultOn:'Fault on {n}', whatsWrong:"What's wrong?", faultPrime:'Lost prime', faultIce:'Iced up', faultPower:'No power', faultOil:'Oil or noise',
  faultPh:'Anything to remember', markFault:'Mark the fault', logFuelN:'Fuel for {n}', fuelNow:'Fuel in the tank now', quickFill:'Quick fill', filledFull:'Filled it, {c} {u}',
  fuelSheetNote:'Log what is in the tank after you fill it. Burn is counted from here.', saveFuelV:'Save {v} {u}', fuelSaved:'Fuel saved, {v} {u}',
  logServiceN:'Service on {n}', whatDone:'What was done', svcOil:'Oil change', svcFilter:'Filter', svcBelt:'Belt', svcClean:'Cleaned', svcPh:'Oil change',
  partsUsedOpt:'Parts used (optional)', partsPh:'1 qt vacuum pump oil', svcHoursNote:'Saved at {h} running hours.', saveService:'Save the service', serviceSaved:'Service saved',
  partsOnHand:'Parts on hand', noParts:'None listed.', partName:'Part name', partPh:'Spare gasket', addW:'Add', fewerOf:'One fewer {n}', moreOf:'One more {n}',
  // Vacuum and leaks
  leakFinder:'Leak finder', leakLede:'A line is a leak suspect when its far end reads {l} in or more under its usual reading ({d} days).',
  leakRuleDefault:'{l} in is a default.', changeInShack:'Change it in Sugar Shack', lineByLine:'Line by line', vsBaseline:'Usual {b} in', oneReading:'One reading so far',
  lookFor:'Look for', look1:'Chewed tubing or drops', look2:'A popped fitting or tee', look3:'A spout pulled out of the tree', look4:'A split from ice',
  // Freeze prep
  freezeNoPlace:'Freeze prep', freezeLoading:'Checking tonight', freezeErrT:"Couldn't get tonight's low", freezeErrP:'The forecast did not load. Try again, or check the pumps anyway if it feels cold.',
  freezeTonightT:'Freeze tonight', readyFreeze:'Ready for the freeze', noFreezeT:'No freeze tonight', needPlaceT:'Set your place first', needPlaceP:'Freeze prep reads the low for your place from the forecast.',
  setPlace:'Set my place', lowTonight:'Low tonight', atOrUnder:'At or under {f}°F', aboveF:'Above {f}°F', freezeRule:'The checklist opens when the low is {f}°F or under. {f}°F is a default you can change in Sugar Shack.',
  beforeFreeze:'Before the freeze · {d} of {t}', beforeFreeze0:'Before the freeze', markAllDone:'Mark all done', prepResets:'The list starts fresh for each night.',
  noPumpsFreezeT:'No pumps yet', noPumpsFreezeP:'The checklist is built from the pumps you add.',
  fzDrainTransfer:'Drain {n}', fzDrainTransferS:'Open the drain plug and let it run dry', fzTrap:'Empty the moisture trap on {n}', fzTrapS:'And the releaser, if it holds sap',
  fzRo:'Flush and drain {n}', fzRoS:'Or keep the room above freezing overnight', fzGen:'Fuel {n} for the night', fzGenS:'So the vacuum keeps running if you run it',
  fzLowDrains:'Open the low drains on the sap lines', fzLowDrainsS:'So sap left in the mainline cannot freeze and split it',
  // Tanks
  tankGoneT:'That tank is gone', tankGoneP:'It was removed, or this link is from another device.', role_collection:'Collection tank', role_storage:'Storage tank', role_concentrate:'Concentrate tank',
  logLevel:'Log the level', tankRateNote:'Two levels a few hours apart give the fill rate and the time it is full.', recentLevels:'Recent levels',
  noLevelsP:'No levels logged yet.', changeTank:'Change this tank', levelOf:'Level in {n}', tankN:'Tank {n}', capacityU:'Holds, {u}', tankRole:'What it holds',
  roleCollection:'Sap', roleStorage:'Storage', roleConc:'Concentrate', tankAdded:'{n} added', tankSaved:'{n} saved', tankLine:'{v} {u} · {p}%', tankPct:'{p}% full',
  // Jobs for Do this next
  jFaultT:'{name} has a fault', jFaultW:'Marked at {since}. It needs you before anything else.', jFaultWn:'{note}. Marked at {since}.', jFaultB:'Open the pump',
  jFaultS:'Since {since}', jFaultSn:'{note}',
  jPrepT:'Freeze prep, {lo}°F tonight', jPrepW:'{left} of {total} freeze jobs still open for tonight.', jPrepB:'Open freeze prep', jPrepS:'{done} of {total} done',
  jFuelT:'{name} is low on fuel', jFuelNT:'{name} runs dry overnight', jFuelW:'About {h} of fuel left. It runs dry near {empty}.', jFuelB:'Log fuel', jFuelS:'{h} left, dry near {empty}',
  jLeakT:'{name} may be leaking', jLeakW:'It read {v} in at the end, {drop} in under its usual {base} in.', jLeakB:'Find it on the map', jLeakS:'{v} in, {drop} in down',
  ctxFault:'{n} has a fault. It needs you first.', ctxLeak:'{n} may have lost vacuum overnight.',
  // Watch
  wTitle:'Sugarbush monitor', wTitleH:'Watch the bush', wOneH:'Watching {n}', wExit:'Exit', wAllLines:'All lines', wManualPill:'Your readings', wDemoPill:'Demo readings, not real',
  wDemoTag:'Demo', wDemoFresh:'Demo · moves every 3 s', wNewest:'Newest reading {a}', wNoReadings:'No readings yet',
  wake_on:'Screen stays on', wake_off:'Screen may sleep', wake_pending:'Keeping the screen on', wake_none:'Screen may sleep',
  wStaleT:'Readings are old', wStaleP:'The newest reading was {a}. Log one from a line or a tank to bring this up to date.',
  wEmptyT:'Nothing to watch yet', wEmptyP:'Watch mode shows your lines, pumps and tanks. Put a mainline on the Bush map or add a pump to start.',
  wEmptyDemo:'To see it move first, turn on Demo readings in Sugar Shack.', wMapAria:'Map of your mainlines coloured by vacuum', wTapLine:'Tap a line for its detail',
  wOutside:'Outside', wTempSrc:'Forecast for {p}', yourPlace:'your place', wNoPlace:'Set your place on Weather watch to see it.', wTempLoading:'Checking…', wTempErr:"Couldn't get it",
  wNoTank:'Add a tank on Pumps to see its level.', wNoPumps:'No pumps yet.', wAlerts:'Alerts', wNoAlerts:'Nothing needs you.', wNoAlertsDemo:'Demo readings raise no alerts.',
  wFault:'{n} fault', wLeak:'{n} leak suspect', wLeakS:'{v} in at the end, {d} in down', wFuel:'{n}: {h} of fuel', dryAt:'Dry near {t}',
  wTankFull:'{n} nearly full', wFreeze:'Freeze tonight, {v}°F', wFreezeS:'{n} jobs open', wLast24:'Last 24 hours', wRecent:'Recent readings', wNeedTwo:'Two readings draw the chart.',
  sapRunning:"Sap's running!", sapRunningS:'{n} rising {v} {u} an hour', sapWeather:'Sap weather', sapWeatherS:"It froze in the last day and it's {t}°F now.",
  sapNotRunning:"Sap's not running", sapNoTemp:'No temperature yet.', sapBelow:"It's below freezing.", sapNoFreeze:'No freeze in the last day.',
  trend_falling:'Falling', trend_rising:'Rising', trend_steady:'Steady', freezeNear:'freeze near {t}', thawNear:'thaw near {t}',
  leakSuspicion:'Leak', susp_suspect:'Suspect', susp_ok:'Low', susp_single:'Needs a second reading', susp_none:'No reading', baselineW:'Usual',
  // Sugar Shack: pumps and alerts
  secOps:'Pumps and alerts', setLeak:'Leak suspect at', setLeakN:'Under the line’s usual reading. Default {d} in.', setFreeze:'Freeze prep at or under', setFreezeN:'Default {d}°F.',
  setFuel:'Warn when fuel runs out within', setStale:'Readings count as old after', setDefaultsN:'These are starting defaults, not rules from a source. Set them to your bush.',
  demoTitle:'Demo readings', demoOffS:'Off. Watch mode shows your own readings.', demoOnS:'On. Watch mode shows made-up numbers so you can see it move. Nothing is saved.',
  demoOnToast:'Demo readings on. Watch mode is showing made-up numbers.', demoOffToast:'Demo readings off',
  // Wide layouts
  backToPumps:'Back to Pumps', tomorrowAt:'tomorrow {t}', runningSince:'Running since {t}', yesterdayAt:'yesterday {t}', opsCard:'Operations', opsNone:'Add a pump or log a line reading to see them here.', kpiStrip:'Right now',
});
Object.assign(RS_TR.fr, {
  bushMap:'Carte de l’érablière', bushLayers:'Couches', addToMap:'Ajouter à la carte', watchBush:'Surveiller l’érablière', mapTools:'Outils de carte',
  lyTrees:'Arbres', lyLaterals:'Latéraux', lyLines:'Lignes', lyVacuum:'Vide', lyBrix:'Brix', lyPumps:'Pompes', lyTanks:'Réservoirs',
  zoomIn:'Zoom avant', zoomOut:'Zoom arrière', doneW:'Terminé', cancelW:'Annuler', undoW:'Annuler le point', saveLine:'Enregistrer la ligne',
  readouts:'Lectures', addPump:'Ajouter une pompe', addTank:'Ajouter un réservoir', stRunning:'En marche', stStopped:'Arrêtée',
  markRunning:'Marquer en marche', markStopped:'Marquer arrêtée', reportFault:'Signaler une panne', logFuel:'Noter le carburant', logService:'Noter un entretien',
  vacAndLeaks:'Vide et fuites', freezePrep:'Préparation au gel', leakFinder:'Détecteur de fuites', logVacuum:'Noter une lecture de vide',
  kind_vacuum:'Vide', kind_transfer:'Transfert', kind_ro:'OI', kind_generator:'Génératrice',
  wTitle:'Moniteur d’érablière', wExit:'Quitter', wAllLines:'Toutes les lignes', wManualPill:'Vos lectures', wDemoPill:'Lectures de démo, pas réelles',
  wOutside:'Dehors', wAlerts:'Alertes', sapRunning:'Ça coule!', sapNotRunning:'Ça ne coule pas', lastChecked:'Dernière vérification', watchLine:'Surveiller cette ligne',
  demoTitle:'Lectures de démo', secOps:'Pompes et alertes', trend_falling:'En baisse', trend_rising:'En hausse', trend_steady:'Stable',
});
